Repository istio/client-go, pull requests merged in 2019-10, with the labels that each got.

#3 Add a gen-check target.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#4 Ensure go.mod is up to date as part of the gen-check target.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#6 Update common files.
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: cla: yes, size/M

#5 use IN_BUILD_CONTAINER instead of BUILD_WITH_CONTAINER to determine i…
  Makefile.core.mk
Labels: cla: yes, size/XS

#7 add an initial readme and update the common files
  Makefile
  README.md
  common/.commonfiles.sha
Labels: cla: yes, size/S

#9 regen before release 1.4
  go.mod
  go.sum
  pkg/apis/rbac/v1alpha1/types.gen.go
Labels: cla: yes, size/S

#8 Update go modules to use the latest patch releases
  go.mod
  go.sum
Labels: cla: yes, size/S

#11 Release 1.4 codeowners, branch, and common-file updates
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#12 Bump dependency version for k8s.io client-go and apimachinery to kubernetes-1.16.2
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  go.mod
  go.sum
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/authentication/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/config/v1alpha2/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/rbac/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/clientset.gen.go
  pkg/clientset/versioned/fake/clientset_generated.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/authentication_client.gen.go
  pkg/clientset/versioned/typed/config/v1alpha2/config_client.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/networking_client.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/rbac_client.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/security_client.gen.go
Labels: cla: yes, size/L
