Repository istio/client-go, pull requests merged in 2019-11, with the labels that each got.

#15 Update istio.io/api to latest
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: cla: yes, size/XS

#16 Added example package to verify generated code
  Makefile.core.mk
  cmd/example/client.go
  go.sum
Labels: cherrypick/release-1.4, cla: yes, size/L

#17 [release-1.4] Added example package to verify generated code
  Makefile.core.mk
  cmd/example/client.go
  go.sum
Labels: cla: yes, size/L

#18 Update api repo to latest release-1.4
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: cla: yes, size/XS

#20 update api version to release-1.4
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  go.mod
  go.sum
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: cla: yes, size/S

#19 update api version
  go.mod
  go.sum
Labels: cla: yes, size/XS

#21 regen for release 1.4
  Makefile
  common/.commonfiles.sha
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: cla: yes, size/XS
