Repository istio/client-go, pull requests merged in 2020-10, with the labels that each got.

#244 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#245 Automator: update common-files@release-1.6 in istio/client-go@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#247 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#246 Bump istio/api
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: cla: yes, size/XS

#248 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#249 Automator: update common-files@release-1.7 in istio/client-go@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#250 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#251 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#252 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#253 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#254 [release-1.8] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#255 Automator: update common-files@release-1.8 in istio/client-go@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#256 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#257 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#258 Manually update istio/api@release-1.8 in istio/client-go@release-1.8
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: cla: yes, size/XS

#259 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#260 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#261 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#262 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
