Repository istio/client-go, pull requests merged in 2020-05, with the labels that each got.

#116 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#117 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#118 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#119 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#120 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#121 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#122 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#123 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#124 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#125 Automator: update common-files@release-1.6 in istio/client-go@release-1.6
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#128 [release-1.6] Update istio/api and run make gen
  go.mod
  go.sum
  pkg/apis/config/v1alpha2/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: cla: yes, size/XS

#126 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/config/v1alpha2/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, size/XS

#129 Automator: update common-files@release-1.6 in istio/client-go@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#130 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#131 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#132 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#133 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#134 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#135 Automator: update common-files@release-1.5 in istio/client-go@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#136 Automator: update istio/api@release-1.5 dependency in istio/client-go@release-1.5
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#137 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#138 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#139 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#140 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#141 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#142 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#143 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#144 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS
