Repository istio/client-go, pull requests merged in 2020-01, with the labels that each got.

#30 Fix client go registration for mixer types
  Makefile
  cmd/example/client.go
  common/.commonfiles.sha
  go.mod
  go.sum
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/config/v1alpha2/register.gen.go
  pkg/apis/config/v1alpha2/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/register.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_requestauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_security_client.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/requestauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/security_client.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/informers/externalversions/security/v1beta1/interface.gen.go
  pkg/informers/externalversions/security/v1beta1/requestauthentication.gen.go
  pkg/listers/security/v1beta1/expansion_generated.gen.go
  pkg/listers/security/v1beta1/requestauthentication.gen.go
Labels: cla: yes, size/M

#31 [release-1.4]Fix client go registration for mixer types
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/report_build_info.sh
  go.mod
  go.sum
  pkg/apis/config/v1alpha2/register.gen.go
  pkg/apis/config/v1alpha2/types.gen.go
Labels: cla: yes, size/L

#32 Automator: update istio/api@master dependency
  go.mod
  go.sum
Labels: cla: yes, size/XS

#33 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: cla: yes, size/XS

#36 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: cla: yes, size/XS

#38 Release 1.5 common files update
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#37 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: cla: yes, size/XS

#42 Release 1.5 codeowners
  CODEOWNERS
  LICENSE
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#40 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: cla: yes, size/XS

#41 Automator: update common-files@master in istio/client-go@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: cla: yes, size/M

#46 Update common file to 1.5 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#39 Update dependencies to latest patch versions
  go.mod
  go.sum
Labels: cla: yes, size/M

#43 Automator: update common-files@master in istio/client-go@master
  Makefile
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: cla: yes, size/M

#44 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/istio.io/api/LICENSE
  pkg/apis/security/v1beta1/register.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_peerauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_security_client.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/peerauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/security_client.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/informers/externalversions/security/v1beta1/interface.gen.go
  pkg/informers/externalversions/security/v1beta1/peerauthentication.gen.go
  pkg/listers/security/v1beta1/expansion_generated.gen.go
  pkg/listers/security/v1beta1/peerauthentication.gen.go
Labels: cla: yes, size/XS

#47 Automator: update istio/api@082bb23 dependency in istio/client-go@master
  go.mod
  go.sum
Labels: cla: yes, size/XS
