Repository istio/client-go, pull requests merged in 2020-04, with the labels that each got.

#87 Update common-file files to `master`
  .gitignore
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/lint_go.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/L

#86 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, size/XS

#89 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#90 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#91 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#92 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#88 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/github.com/census-instrumentation/opencensus-proto/LICENSE
  licenses/github.com/cncf/udpa/go/LICENSE
  licenses/github.com/envoyproxy/go-control-plane/LICENSE
  licenses/github.com/envoyproxy/protoc-gen-validate/LICENSE
  licenses/github.com/prometheus/client_model/LICENSE
  licenses/github.com/prometheus/client_model/ruby/LICENSE
Labels: auto-merge, cla: yes, size/XXL

#95 Remove Policy and MeshPolicy in client go
  Makefile.core.mk
  cmd/example/client.go
  go.mod
  go.sum
  pkg/apis/authentication/v1alpha1/doc.go
  pkg/apis/authentication/v1alpha1/register.gen.go
  pkg/apis/authentication/v1alpha1/types.gen.go
  pkg/apis/authentication/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/clientset.gen.go
  pkg/clientset/versioned/fake/clientset_generated.gen.go
  pkg/clientset/versioned/fake/register.gen.go
  pkg/clientset/versioned/scheme/register.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/authentication_client.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/doc.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/fake/doc.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/fake/fake_authentication_client.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/fake/fake_meshpolicy.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/fake/fake_policy.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/meshpolicy.gen.go
  pkg/clientset/versioned/typed/authentication/v1alpha1/policy.gen.go
  pkg/informers/externalversions/authentication/interface.gen.go
  pkg/informers/externalversions/authentication/v1alpha1/interface.gen.go
  pkg/informers/externalversions/authentication/v1alpha1/meshpolicy.gen.go
  pkg/informers/externalversions/authentication/v1alpha1/policy.gen.go
  pkg/informers/externalversions/factory.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/listers/authentication/v1alpha1/expansion_generated.gen.go
  pkg/listers/authentication/v1alpha1/meshpolicy.gen.go
  pkg/listers/authentication/v1alpha1/policy.gen.go
Labels: cla: yes, size/M

#96 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#94 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#97 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#98 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#99 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#100 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#101 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#102 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#103 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#104 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#105 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#106 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#107 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#108 Add release managers to 1.6 branch; change common files
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#109 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#110 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#111 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#112 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#113 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#114 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#115 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS
