Repository istio/client-go, pull requests merged in 2020-06, with the labels that each got.

#145 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#146 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#147 refactor: remove rbac API group from client-go
  Makefile.core.mk
  pkg/apis/rbac/v1alpha1/doc.go
  pkg/apis/rbac/v1alpha1/register.gen.go
  pkg/apis/rbac/v1alpha1/types.gen.go
  pkg/apis/rbac/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/clientset.gen.go
  pkg/clientset/versioned/fake/clientset_generated.gen.go
  pkg/clientset/versioned/fake/register.gen.go
  pkg/clientset/versioned/scheme/register.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/clusterrbacconfig.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/doc.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/doc.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/fake_clusterrbacconfig.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/fake_rbac_client.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/fake_rbacconfig.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/fake_servicerole.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/fake/fake_servicerolebinding.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/rbac_client.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/rbacconfig.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/servicerole.gen.go
  pkg/clientset/versioned/typed/rbac/v1alpha1/servicerolebinding.gen.go
  pkg/informers/externalversions/factory.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/informers/externalversions/rbac/interface.gen.go
  pkg/informers/externalversions/rbac/v1alpha1/clusterrbacconfig.gen.go
  pkg/informers/externalversions/rbac/v1alpha1/interface.gen.go
  pkg/informers/externalversions/rbac/v1alpha1/rbacconfig.gen.go
  pkg/informers/externalversions/rbac/v1alpha1/servicerole.gen.go
  pkg/informers/externalversions/rbac/v1alpha1/servicerolebinding.gen.go
  pkg/listers/rbac/v1alpha1/clusterrbacconfig.gen.go
  pkg/listers/rbac/v1alpha1/expansion_generated.gen.go
  pkg/listers/rbac/v1alpha1/rbacconfig.gen.go
  pkg/listers/rbac/v1alpha1/servicerole.gen.go
  pkg/listers/rbac/v1alpha1/servicerolebinding.gen.go
Labels: cla: yes, ok-to-test, size/M

#148 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#149 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#150 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#151 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#152 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#153 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#155 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#156 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#157 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#158 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#159 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#160 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#162 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#165 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#166 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#167 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#169 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#170 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#171 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#168 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, size/XS

#172 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#173 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#174 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#175 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#176 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#177 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#178 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#179 Automator: update istio/api@release-1.6 dependency in istio/client-go@release-1.6
  go.mod
  go.sum
Labels: auto-merge, cla: yes, size/XS

#180 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
