Repository istio/client-go, pull requests merged in 2020-08, with the labels that each got.

#205 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/report_build_info.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#212 Automator: update common-files@release-1.7 in istio/client-go@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#213 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#214 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#215 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#217 [release-1.7] Update API version
  go.mod
  go.sum
Labels: cla: yes, size/XS

#218 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#219 Automator: update common-files@release-1.7 in istio/client-go@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#221 Automator: update common-files@release-1.7 in istio/client-go@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#222 move client-go ownership to UX
  CODEOWNERS
Labels: cla: yes, size/XS

#216 Update API version
  go.mod
  go.sum
Labels: cla: yes, size/XS

#223 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#224 Generate WorkloadGroup changes
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/register.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_networking_client.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_workloadgroup.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/generated_expansion.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/networking_client.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/workloadgroup.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/informers/externalversions/networking/v1alpha3/interface.gen.go
  pkg/informers/externalversions/networking/v1alpha3/workloadgroup.gen.go
  pkg/listers/networking/v1alpha3/expansion_generated.gen.go
  pkg/listers/networking/v1alpha3/workloadgroup.gen.go
Labels: cla: yes, size/XS

#225 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#226 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#227 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#228 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
