Repository istio/client-go, pull requests merged in 2021-12, with the labels that each got.

#697 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#698 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#699 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#700 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#701 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#702 Automator: update common-files@release-1.12 in istio/client-go@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#703 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#704 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#705 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#706 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#707 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#710 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#711 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#712 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#709 Update to latest api and also k8s.client-go
  go.mod
  go.sum
  licenses/github.com/hashicorp/golang-lru/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
  licenses/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  licenses/k8s.io/client-go/third_party/forked/golang/LICENSE
  licenses/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  licenses/sigs.k8s.io/json/LICENSE
Labels: size/XXL

#708 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#713 Automator: update common-files@release-1.12 in istio/client-go@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#714 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#716 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#717 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#715 Update client-go to use generators from k8s 1.23
  pkg/clientset/versioned/clientset.gen.go
  pkg/clientset/versioned/fake/clientset_generated.gen.go
  pkg/clientset/versioned/fake/register.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/extensions_client.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/fake/fake_wasmplugin.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_destinationrule.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_envoyfilter.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_gateway.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_serviceentry.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_sidecar.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_virtualservice.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_workloadentry.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_workloadgroup.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/networking_client.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_destinationrule.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_gateway.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_proxyconfig.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_serviceentry.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_sidecar.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_virtualservice.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_workloadentry.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/networking_client.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_authorizationpolicy.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_peerauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_requestauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/security_client.gen.go
  pkg/clientset/versioned/typed/telemetry/v1alpha1/fake/fake_telemetry.gen.go
  pkg/clientset/versioned/typed/telemetry/v1alpha1/telemetry_client.gen.go
  pkg/listers/extensions/v1alpha1/wasmplugin.gen.go
  pkg/listers/networking/v1alpha3/destinationrule.gen.go
  pkg/listers/networking/v1alpha3/envoyfilter.gen.go
  pkg/listers/networking/v1alpha3/gateway.gen.go
  pkg/listers/networking/v1alpha3/serviceentry.gen.go
  pkg/listers/networking/v1alpha3/sidecar.gen.go
  pkg/listers/networking/v1alpha3/virtualservice.gen.go
  pkg/listers/networking/v1alpha3/workloadentry.gen.go
  pkg/listers/networking/v1alpha3/workloadgroup.gen.go
  pkg/listers/networking/v1beta1/destinationrule.gen.go
  pkg/listers/networking/v1beta1/gateway.gen.go
  pkg/listers/networking/v1beta1/proxyconfig.gen.go
  pkg/listers/networking/v1beta1/serviceentry.gen.go
  pkg/listers/networking/v1beta1/sidecar.gen.go
  pkg/listers/networking/v1beta1/virtualservice.gen.go
  pkg/listers/networking/v1beta1/workloadentry.gen.go
  pkg/listers/security/v1beta1/authorizationpolicy.gen.go
  pkg/listers/security/v1beta1/peerauthentication.gen.go
  pkg/listers/security/v1beta1/requestauthentication.gen.go
  pkg/listers/telemetry/v1alpha1/telemetry.gen.go
Labels: size/XS

#719 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#720 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#721 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#722 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#723 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
