Repository istio/client-go, pull requests merged in 2021-08, with the labels that each got.

#576 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#577 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#512 Add types for extensions.istio.io
  Makefile.core.mk
  pkg/apis/extensions/v1alpha1/doc.go
  pkg/apis/extensions/v1alpha1/register.gen.go
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/clientset/versioned/clientset.gen.go
  pkg/clientset/versioned/fake/clientset_generated.gen.go
  pkg/clientset/versioned/fake/register.gen.go
  pkg/clientset/versioned/scheme/register.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/doc.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/extensions_client.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/fake/doc.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/fake/fake_wasmplugin.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/wasmplugin.gen.go
  pkg/informers/externalversions/extensions/interface.gen.go
  pkg/informers/externalversions/extensions/v1alpha1/interface.gen.go
  pkg/informers/externalversions/extensions/v1alpha1/wasmplugin.gen.go
  pkg/informers/externalversions/factory.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/listers/extensions/v1alpha1/expansion_generated.gen.go
  pkg/listers/extensions/v1alpha1/wasmplugin.gen.go
Labels: cla: yes, size/M

#578 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#579 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#580 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#581 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#582 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#583 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#584 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#585 Automator: update common-files@release-1.11 in istio/client-go@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#586 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#587 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#588 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#589 Failed update of common files
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#590 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, cla: yes, auto-merge, release-notes-none

#591 Automator: update istio/api@release-1.10 dependency in istio/client-go@release-1.10
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#592 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#593 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#596 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#597 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, cla: yes, auto-merge, release-notes-none
