Repository istio/client-go, pull requests merged in 2021-04, with the labels that each got.

#427 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#428 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#429 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#430 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#431 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#432 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#433 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#434 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#435 Automator: update istio/api@release-1.10 dependency in istio/client-go@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#436 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#437 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#439 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#438 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#440 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#441 Automator: update common-files@release-1.8 in istio/client-go@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#442 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#443 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#444 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#445 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#446 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#448 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#449 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#450 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#451 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#452 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#453 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#454 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#455 Automator: update istio/api@release-1.10 dependency in istio/client-go@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#456 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#457 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#458 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#459 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#460 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#461 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#462 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#463 Update k8s libraries to v0.21.0 to keep in line with istio.io/istio
  go.mod
  go.sum
  licenses/golang.org/x/term/LICENSE
Labels: cla: yes, size/M

#464 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#465 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS
