Repository istio/client-go, pull requests merged in 2021-01, with the labels that each got.

#311 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#312 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#313 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#315 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#316 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#317 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#318 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#319 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#320 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#321 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#322 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#323 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#324 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/S

#325 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#326 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#327 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#328 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#329 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#330 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#331 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#332 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#333 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#334 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#336 Update common/Makefile.common.mk to point to release-1.9
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#335 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#337 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#338 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#339 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#340 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#341 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#344 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#343 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#345 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#346 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#347 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/istio.io/gogo-genproto/LICENSE
Labels: auto-merge, cla: yes, release-notes-none, size/M

#348 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#349 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#350 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#351 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#352 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#353 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#354 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#355 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#356 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#357 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#359 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#360 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#361 Automator: update common-files@master in istio/client-go@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#362 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#363 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#364 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#365 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#366 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#367 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#368 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#369 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#370 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#371 Automator: update common-files@release-1.8 in istio/client-go@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#372 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#373 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#374 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#375 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#376 Automator: update common-files@release-1.7 in istio/client-go@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#377 Automator: update istio/api@release-1.7 dependency in istio/client-go@release-1.7
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#378 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#379 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#380 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#381 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/M

#382 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#384 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS
