Repository istio/client-go, pull requests merged in 2021-02, with the labels that each got.

#383 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/M

#385 Add IDE artifacts to .gitignore
  .gitignore
Labels: cla: yes, ok-to-test, size/S

#386 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#387 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#388 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#389 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#390 Automator: update common-files@release-1.8 in istio/client-go@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#391 Automator: update istio/api@release-1.8 dependency in istio/client-go@release-1.8
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#392 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#393 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#394 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#396 [release-1.9] Update go.mod with istio/istio@release-1.9 dependencies
  go.mod
  go.sum
  licenses/github.com/evanphx/json-patch/LICENSE
  licenses/github.com/go-logr/logr/LICENSE
  licenses/github.com/pkg/errors/LICENSE
  licenses/google.golang.org/protobuf/LICENSE
  licenses/k8s.io/klog/v2/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/errors/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/spec/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/strfmt/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/validate/LICENSE
  licenses/sigs.k8s.io/structured-merge-diff/v4/LICENSE
Labels: cla: yes, size/XXL

#395 Update k8s dependencies
  go.mod
  go.sum
  licenses/github.com/evanphx/json-patch/LICENSE
  licenses/github.com/go-logr/logr/LICENSE
  licenses/github.com/pkg/errors/LICENSE
  licenses/google.golang.org/protobuf/LICENSE
  licenses/k8s.io/klog/v2/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/errors/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/spec/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/strfmt/LICENSE
  licenses/k8s.io/kube-openapi/pkg/validation/validate/LICENSE
  licenses/sigs.k8s.io/structured-merge-diff/v4/LICENSE
Labels: cla: yes, size/XXL

#397 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#398 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/M

#399 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#400 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS
