Repository istio/client-go, pull requests merged in 2021-07, with the labels that each got.

#541 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#542 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#543 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#544 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#545 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#546 Automator: update istio/api@release-1.10 dependency in istio/client-go@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#547 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#548 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#549 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#550 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#551 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#552 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#553 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#554 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#555 Automator: update common-files@release-1.9 in istio/client-go@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#556 Automator: update istio/api@release-1.9 dependency in istio/client-go@release-1.9
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#557 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#558 Update api in client-go
  go.mod
  go.sum
Labels: cla: yes, size/XS

#559 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#560 Automator: update istio/api@release-1.10 dependency in istio/client-go@release-1.10
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#562 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#561 [release-1.11] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#563 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#564 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#565 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#566 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#567 Automator: update common-files@release-1.10 in istio/client-go@release-1.10
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#568 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#569 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#570 Automator: update common-files@release-1.11 in istio/client-go@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#571 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#572 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#573 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#574 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#575 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: auto-merge, cla: yes, release-notes-none, size/XS
