Repository istio/client-go, pull requests merged in 2022-01, with the labels that each got.

#724 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#725 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#726 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#727 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#728 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#729 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#730 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/register.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/networking/v1beta1/zz_generated.deepcopy.gen.go
  pkg/applyconfiguration/networking/v1beta1/workloadgroup.go
  pkg/applyconfiguration/utils.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_networking_client.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_workloadgroup.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/generated_expansion.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/networking_client.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/workloadgroup.gen.go
  pkg/informers/externalversions/generic.gen.go
  pkg/informers/externalversions/networking/v1beta1/interface.gen.go
  pkg/informers/externalversions/networking/v1beta1/workloadgroup.gen.go
  pkg/listers/networking/v1beta1/expansion_generated.gen.go
  pkg/listers/networking/v1beta1/workloadgroup.gen.go
Labels: size/L, auto-merge, release-notes-none

#731 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#732 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/networking/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#733 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#734 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#735 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#736 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#737 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#738 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#739 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#740 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#741 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#742 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#743 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#744 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#746 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#747 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#748 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#745 [release-1.13] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#749 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#750 Automator: update common-files@release-1.12 in istio/client-go@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#751 Automator: update common-files@release-1.13 in istio/client-go@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#752 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#753 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#754 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#755 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#756 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#757 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#758 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#759 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#760 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/lint_go.sh
Labels: size/XS, auto-merge, release-notes-none

#761 Automator: update common-files@release-1.11 in istio/client-go@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#762 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#763 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#764 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#765 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#766 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#767 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#768 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#769 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
