Repository istio/client-go, pull requests merged in 2022-10, with the labels that each got.

#1151 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1152 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1153 Automator: update common-files@release-1.14 in istio/client-go@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1154 Automator: update istio/api@release-1.14 dependency in istio/client-go@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1155 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1156 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1157 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/istio.io/api/LICENSE
Labels: size/XS, auto-merge, release-notes-none

#1158 Automator: update common-files@master in istio/client-go@master
  LICENSE
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1159 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1160 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1161 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1162 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1163 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1164 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1165 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1166 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1167 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1168 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1169 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1170 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1171 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1172 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1173 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1174 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1175 [release-1.16] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1176 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1177 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1178 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1179 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1181 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#1180 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1183 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1184 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1186 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1187 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1188 Manual update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/report_build_info.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS

#1189 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1190 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1191 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#1192 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1193 Update dependencies; run make gen
  go.mod
  go.sum
  licenses/github.com/PuerkitoBio/purell/LICENSE
  licenses/github.com/PuerkitoBio/urlesc/LICENSE
  licenses/github.com/emicklei/go-restful/v3/LICENSE
  licenses/github.com/go-openapi/jsonpointer/LICENSE
  licenses/github.com/go-openapi/jsonreference/LICENSE
  licenses/github.com/go-openapi/swag/LICENSE
  licenses/github.com/josharian/intern/license.md
  licenses/github.com/mailru/easyjson/LICENSE
  licenses/github.com/munnerz/goautoneg/LICENSE
Labels: size/XL

#1194 Fix go mod tidy issue in istio/api
  go.mod
  go.sum
Labels: size/L

#1197 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1196 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#1198 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1199 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1200 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1201 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1202 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1203 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1204 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1205 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1206 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1207 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
