Repository istio/client-go, pull requests merged in 2022-08, with the labels that each got.

#1063 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1064 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1065 Automator: update istio/api@release-1.14 dependency in istio/client-go@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1066 Automator: update common-files@release-1.14 in istio/client-go@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1067 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1068 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1069 Automator: update common-files@release-1.14 in istio/client-go@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1070 Automator: update istio/api@release-1.14 dependency in istio/client-go@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1072 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1073 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1075 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1074 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1076 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1078 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1071 [release-1.15] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1079 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1080 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1081 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1082 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1083 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1085 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1086 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1087 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
  pkg/clientset/versioned/fake/register.gen.go
  pkg/clientset/versioned/scheme/register.gen.go
Labels: size/XS, auto-merge, release-notes-none

#1088 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1089 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1090 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1091 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1092 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1093 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1094 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1095 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1096 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1097 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1098 Automator: update istio/api@release-1.14 dependency in istio/client-go@release-1.14
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1099 Automator: update common-files@release-1.14 in istio/client-go@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1100 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1101 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1102 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1103 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1104 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1105 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1106 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#1108 Automator: update common-files@release-1.13 in istio/client-go@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1109 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1110 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1111 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1112 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1113 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1114 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1115 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1116 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
