Repository istio/client-go, pull requests merged in 2022-03, with the labels that each got.

#813 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#814 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#815 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#817 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#818 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#819 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#820 Automator: update common-files@release-1.13 in istio/client-go@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#822 Automator: update common-files@release-1.12 in istio/client-go@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#821 Automator: update istio/api@release-1.13 dependency in istio/client-go@release-1.13
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#823 Automator: update istio/api@release-1.12 dependency in istio/client-go@release-1.12
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#824 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#825 Automator: update common-files@release-1.11 in istio/client-go@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#826 Automator: update istio/api@release-1.11 dependency in istio/client-go@release-1.11
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#827 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#828 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#829 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#830 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#832 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#833 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#834 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#835 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/S, auto-merge, release-notes-none

#836 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#837 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#838 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#839 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#841 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#842 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#843 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#844 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#845 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#846 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#848 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#849 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#850 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#851 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#852 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#853 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#854 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#855 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#856 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#857 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#860 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#859 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#861 Support golang/protobuf
  Makefile.core.mk
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/networking/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/telemetry/v1alpha1/types.gen.go
  pkg/apis/telemetry/v1alpha1/zz_generated.deepcopy.gen.go
Labels: size/XS

#862 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/google.golang.org/genproto/LICENSE
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/S, auto-merge, release-notes-none

#864 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#863 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#865 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#866 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#867 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#868 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#869 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#870 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#871 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#873 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#872 Golang 1.16 is now EOL. Migrate to 1.17 go.mod files
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
Labels: size/M

#874 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#875 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#876 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
