Repository istio/client-go, pull requests merged in 2023-04, with the labels that each got.

#1484 Manual update of istio/api for failing go get on specific commit
  go.mod
  go.sum
Labels: size/XS

#1485 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1486 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1487 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#1488 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1489 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1491 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1492 Automator: update common-files@release-1.17 in istio/client-go@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1493 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1494 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1495 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1496 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1497 Update deps 2023-04-10
  go.mod
  go.sum
Labels: size/S

#1499 Manual update of istio/api (pipeline is failing)
  go.mod
  go.sum
Labels: size/XS

#1500 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#1502 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1503 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1501 Update deps to k8s 1.27.0
  go.mod
  go.sum
  licenses/github.com/google/uuid/LICENSE
Labels: size/L

#1505 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1507 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/clientset/versioned/doc.go
  pkg/clientset/versioned/typed/extensions/v1alpha1/fake/fake_wasmplugin.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_destinationrule.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_envoyfilter.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_gateway.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_serviceentry.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_sidecar.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_virtualservice.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_workloadentry.gen.go
  pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_workloadgroup.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_destinationrule.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_gateway.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_proxyconfig.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_serviceentry.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_sidecar.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_virtualservice.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_workloadentry.gen.go
  pkg/clientset/versioned/typed/networking/v1beta1/fake/fake_workloadgroup.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_authorizationpolicy.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_peerauthentication.gen.go
  pkg/clientset/versioned/typed/security/v1beta1/fake/fake_requestauthentication.gen.go
  pkg/clientset/versioned/typed/telemetry/v1alpha1/fake/fake_telemetry.gen.go
Labels: size/S, auto-merge, release-notes-none

#1509 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1510 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1513 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1514 [release-1.18] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#1515 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1516 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1517 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1518 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1519 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1520 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
