Repository istio/client-go, pull requests merged in 2023-05, with the labels that each got.

#1522 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1523 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1524 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1525 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1526 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1527 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1528 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1529 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1530 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1531 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1532 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1533 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1534 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1536 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1539 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1540 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1541 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1542 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1544 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1545 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1543 [CNCF graduation] Add security tab for Istio repos
  .github/SECURITY.md
Labels: size/XS

#1547 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1548 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1550 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1549 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1552 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1553 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1554 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1557 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1558 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1559 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/S, auto-merge, release-notes-none

#1560 Automator: update common-files@release-1.17 in istio/client-go@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1561 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1562 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1563 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1566 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1567 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1568 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
