Repository istio/client-go, pull requests merged in 2023-12, with the labels that each got.

#1866 Automator: update istio/api@release-1.20 dependency in istio/client-go@release-1.20
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1867 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1868 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1869 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1870 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1871 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1872 Automator: update common-files@release-1.20 in istio/client-go@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1873 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1874 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1876 Automator: update istio/api@release-1.20 dependency in istio/client-go@release-1.20
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1878 Automator: update istio/api@release-1.20 dependency in istio/client-go@release-1.20
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1880 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1881 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1882 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1883 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1884 updates for k8s 1.29
  go.mod
  go.sum
  pkg/informers/externalversions/factory.gen.go
Labels: size/M

#1885 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#1886 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1887 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1888 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
