Repository istio/client-go, pull requests merged in 2023-03, with the labels that each got.

#1438 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1439 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1440 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1441 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1442 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1443 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1444 Automator: update common-files@master in istio/client-go@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1445 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1447 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1448 Manually update to latest istio/api
  go.mod
  go.sum
Labels: size/XS

#1449 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1450 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1451 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1452 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1454 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1453 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1455 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1457 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1458 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1459 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1460 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1461 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1462 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1464 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#1465 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1466 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1468 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1469 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1470 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1471 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1472 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1473 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1474 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1475 Automator: update common-files@release-1.17 in istio/client-go@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1476 Automator: update istio/api@release-1.15 dependency in istio/client-go@release-1.15
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1478 Automator: update istio/api@release-1.16 dependency in istio/client-go@release-1.16
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1477 Automator: update common-files@release-1.15 in istio/client-go@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1479 Automator: update common-files@release-1.16 in istio/client-go@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1480 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1481 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#1482 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
