Repository istio/client-go, pull requests merged in 2023-08, with the labels that each got.

#1686 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1687 Automator: update common-files@release-1.17 in istio/client-go@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1688 Automator: update istio/api@release-1.17 dependency in istio/client-go@release-1.17
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1689 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1690 Automator: update istio/api@release-1.18 dependency in istio/client-go@release-1.18
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1691 Automator: update common-files@release-1.18 in istio/client-go@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1697 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1696 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#1698 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1699 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1700 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1701 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1702 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1703 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1704 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1706 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1707 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1709 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1710 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1711 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1712 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1713 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1714 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1716 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1717 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1718 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1719 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1720 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1722 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1723 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1724 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1725 Make gen with k8s 1.28 tooling
  pkg/informers/externalversions/factory.gen.go
Labels: size/XS

#1726 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/github.com/google/gnostic-models/LICENSE
  licenses/google.golang.org/genproto/googleapis/api/LICENSE
Labels: size/L, auto-merge, release-notes-none

#1727 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1728 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1730 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
  licenses/github.com/google/gnostic-models/LICENSE
  pkg/informers/externalversions/factory.gen.go
Labels: size/L, auto-merge, release-notes-none

#1731 Update dependencies to k8s 1.28
  go.mod
  go.sum
  licenses/github.com/google/gnostic/LICENSE
Labels: size/XL

#1729 [release-1.19] Run make gen on release-1.19
  go.mod
  go.sum
  licenses/github.com/google/gnostic/LICENSE
Labels: size/XL

#1732 Automator: update istio/api@release-1.19 dependency in istio/client-go@release-1.19
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1733 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1734 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1735 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1736 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1737 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1738 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1741 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1742 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1743 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#1744 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1745 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1746 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1747 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1748 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1749 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#1750 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
