Repository istio/client-go, pull requests merged in 2024-12, with the labels that each got.

#2300 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2301 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2302 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2303 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2304 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2305 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2307 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2308 Automator: update istio/api@release-1.22 dependency in istio/client-go@release-1.22
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2309 Automator: update common-files@release-1.22 in istio/client-go@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2311 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2313 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2314 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2315 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2316 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2317 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2318 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2319 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2320 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2321 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2323 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2325 Automator: update common-files@release-1.24 in istio/client-go@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2326 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2327 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2328 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2329 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2330 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2331 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2332 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2333 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  licenses/golang.org/x/net/LICENSE
  licenses/golang.org/x/sys/LICENSE
  licenses/golang.org/x/term/LICENSE
  licenses/golang.org/x/text/LICENSE
Labels: size/M, auto-merge, release-notes-none

#2334 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2336 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2337 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2338 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2322 codegen: fix DeepCopy races
  Makefile.core.mk
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/telemetry/v1/zz_generated.deepcopy.gen.go
  pkg/apis/telemetry/v1alpha1/zz_generated.deepcopy.gen.go
Labels: size/XS, cherrypick/release-1.24

#2339 [release-1.24] codegen: fix DeepCopy races
  Makefile.core.mk
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go
  pkg/apis/networking/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1/zz_generated.deepcopy.gen.go
  pkg/apis/security/v1beta1/zz_generated.deepcopy.gen.go
  pkg/apis/telemetry/v1/zz_generated.deepcopy.gen.go
  pkg/apis/telemetry/v1alpha1/zz_generated.deepcopy.gen.go
Labels: size/XS, release-notes-none

#2340 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2341 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
