Repository istio/client-go, pull requests merged in 2024-05, with the labels that each got.

#2072 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2073 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2074 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2076 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2075 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2077 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2079 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2080 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2081 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2082 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2083 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2084 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2087 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2088 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2089 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2090 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2091 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2092 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2093 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/telemetry/v1/types.gen.go
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2094 Automator: update common-files@release-1.20 in istio/client-go@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2095 Automator: update istio/api@release-1.20 dependency in istio/client-go@release-1.20
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2096 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2097 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2098 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2099 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2100 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#2101 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2102 Automator: update istio/api@release-1.22 dependency in istio/client-go@release-1.22
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2103 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2104 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2105 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2108 Automator: update istio/api@release-1.22 dependency in istio/client-go@release-1.22
  go.mod
  go.sum
  pkg/apis/security/v1beta1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2106 Regen with latest plugin
  pkg/apis/networking/v1/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/telemetry/v1/types.gen.go
  pkg/applyconfiguration/networking/v1/destinationrule.go
  pkg/applyconfiguration/networking/v1/gateway.go
  pkg/applyconfiguration/networking/v1/serviceentry.go
  pkg/applyconfiguration/networking/v1/sidecar.go
  pkg/applyconfiguration/networking/v1/virtualservice.go
  pkg/applyconfiguration/networking/v1/workloadentry.go
  pkg/applyconfiguration/networking/v1/workloadgroup.go
  pkg/applyconfiguration/networking/v1beta1/destinationrule.go
  pkg/applyconfiguration/networking/v1beta1/gateway.go
  pkg/applyconfiguration/networking/v1beta1/serviceentry.go
  pkg/applyconfiguration/networking/v1beta1/sidecar.go
  pkg/applyconfiguration/networking/v1beta1/virtualservice.go
  pkg/applyconfiguration/networking/v1beta1/workloadentry.go
  pkg/applyconfiguration/networking/v1beta1/workloadgroup.go
  pkg/applyconfiguration/security/v1/authorizationpolicy.go
  pkg/applyconfiguration/security/v1/peerauthentication.go
  pkg/applyconfiguration/security/v1/requestauthentication.go
  pkg/applyconfiguration/telemetry/v1/telemetry.go
Labels: size/L, release-notes-none

#2107 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2109 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/networking/v1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/telemetry/v1/types.gen.go
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2110 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2111 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2112 Automator: update istio/api@release-1.22 dependency in istio/client-go@release-1.22
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2113 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2114 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2115 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2116 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2117 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2118 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2120 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2121 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2122 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
