Repository istio/client-go, pull requests merged in 2024-04, with the labels that each got.

#2031 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2032 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2033 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2034 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2035 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#2036 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2037 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2038 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2039 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2040 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2041 Automator: update common-files@release-1.21 in istio/client-go@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2043 Automator: update common-files@release-1.20 in istio/client-go@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2042 Automator: update istio/api@release-1.21 dependency in istio/client-go@release-1.21
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2044 Automator: update istio/api@release-1.20 dependency in istio/client-go@release-1.20
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2045 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#2046 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2047 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2048 Automator: update common-files@release-1.19 in istio/client-go@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2051 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2052 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2053 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2054 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2055 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2056 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2057 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2058 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2059 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2060 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2062 Automator: update istio/api@release-1.21 dependency in istio/client-go@release-1.21
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2063 [release-1.22] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#2064 [release-1.22] Fixup common-files
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS

#2065 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2066 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#2067 Automator: update istio/api@release-1.22 dependency in istio/client-go@release-1.22
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2068 [release-1.22] Update common files due to failed job with old image
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS

#2069 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2070 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
