Repository istio/client-go, pull requests merged in 2025-02, with the labels that each got.

#2359 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2360 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2361 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2364 Automator: update istio/api@release-1.25 dependency in istio/client-go@release-1.25
  go.mod
  go.sum
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/telemetry/v1/types.gen.go
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2365 Automator: update istio/api@release-1.25 dependency in istio/client-go@release-1.25
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2363 make gen
  pkg/apis/extensions/v1alpha1/types.gen.go
  pkg/apis/networking/v1/types.gen.go
  pkg/apis/networking/v1alpha3/types.gen.go
  pkg/apis/networking/v1beta1/types.gen.go
  pkg/apis/security/v1/types.gen.go
  pkg/apis/security/v1beta1/types.gen.go
  pkg/apis/telemetry/v1/types.gen.go
  pkg/apis/telemetry/v1alpha1/types.gen.go
Labels: size/XS, cherrypick/release-1.25

#2362 [release-1.25] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#2367 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2368 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2369 Automator: update common-files@release-1.25 in istio/client-go@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2370 Automator: update istio/api@release-1.25 dependency in istio/client-go@release-1.25
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2371 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2372 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2373 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2374 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2375 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2377 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2378 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2379 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2380 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2381 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2382 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2383 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2384 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2385 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2386 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
