Repository istio/client-go, pull requests merged in 2025-04, with the labels that each got.

#2413 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2414 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2409 Automator: update common-files@release-1.23 in istio/client-go@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2415 Automator: update istio/api@release-1.23 dependency in istio/client-go@release-1.23
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2416 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2417 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2419 Automator: update istio/api@release-1.23 dependency in istio/client-go@release-1.23
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2420 Automator: update common-files@release-1.24 in istio/client-go@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2421 Automator: update istio/api@release-1.24 dependency in istio/client-go@release-1.24
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2422 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2423 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#2425 Automator: update common-files@master in istio/client-go@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2424 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2426 Automator: update common-files@release-1.25 in istio/client-go@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2427 Automator: update istio/api@release-1.25 dependency in istio/client-go@release-1.25
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2428 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2429 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2431 Automator: update istio/api@release-1.26 dependency in istio/client-go@release-1.26
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2430 [release-1.26] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#2432 Automator: update istio/api@release-1.26 dependency in istio/client-go@release-1.26
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2434 Automator: update common-files@release-1.26 in istio/client-go@release-1.26
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2435 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2436 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#2437 Automator: update common-files@master in istio/client-go@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2438 Automator: update istio/api@master dependency in istio/client-go@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
